### ISSUE TITLE
Terminar o menu

### ISSUE THREAD

**Issue by AlvaroLQueiroz** [IgoRode/QuimicaEZ#12]

**Comment by IgoRode** [comment]
esse aqui é hard

**Comment by IgoRode** [comment]
![image](https://user-images.githubusercontent.com/44612599/57264843-5eac1880-7042-11e9-8c8e-6a2406454dea.png)
65%

**Comment by IgoRode** [comment]
parece feio??parece, porem ta quase

**Comment by IgoRode** [comment]
![image](https://user-images.githubusercontent.com/44612599/57662381-45b0e380-75bd-11e9-92ea-500b10c696f8.png)

**Comment by IgoRode** [comment]
DEFINITIVOS 50% ps:.agora ta bonitinho
