### ISSUE TITLE
Adicionar caixa laranja na tela de facepage

### ISSUE THREAD

**Issue by AlvaroLQueiroz** [IgoRode/QuimicaEZ#3]

**Comment by IgoRode** [comment]
Eu tentei e fico feio para caramba ae decidi deixar sem por hora

**Comment by AlvaroLQueiroz** [comment]
Vamos procurar uma cor que fica melhor pro texto.

**Comment by IgoRode** [comment]
![image](https://user-images.githubusercontent.com/44612599/57258204-c013bd80-7029-11e9-980a-722b2ffe1631.png)

**Comment by IgoRode** [comment]
![image](https://user-images.githubusercontent.com/44612599/57258353-2e588000-702a-11e9-9a05-6662b5ad4d1e.png)
